version: "3.0"

volumes:
  db-data:
    external: false

services:

  db:
    image: mariadb:10.4
    ports:
      - 3306:3306
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: stevedb
      MYSQL_USER: steve
      MYSQL_PASSWORD: changeme

  app:
    build: .
    links:
      - "db:mariadb"
    volumes:
      - .:/code
    ports:
      - "8180:8180"
      - "8443:8443"
    environment:
      AZURE_CLIENT_SECRET: iDqur-r0Ju0hbHCwxy8DAOwMGoylI8COoj
      AZURE_CLIENT_ID: e151b7a2-c889-4962-814f-5ba1a1c72a42
      AZURE_TENANT_ID: 188263d3-9acb-46f8-80e0-78d979283817
      DB_HOST: mariadb
      DB_PORT: 3306
      DB_DATABASE: stevedb
      DB_USERNAME: steve
      DB_PASSWORD: changeme
    depends_on:
      - db
